import localFont from "next/font/local";
import "./globals.css";
import Layout from "./components/Layout";
import { fetchBlogs } from "../services/firebaseService";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


async function getBlogs() {
  try {
    const blogs = await fetchBlogs();
    return blogs[0].items;
  } catch (error) {
    console.error('Error fetching blog data:', error);
    return [];
  }
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const blogs = await getBlogs();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Layout blogs={blogs}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
