import localFont from "next/font/local";
import "./globals.css";
import Layout from "./components/Layout";
import { fetchBlogs } from "../services/firebaseService";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export async function getStaticProps() {
  try {
    const blogs = await fetchBlogs();
    return {
      props: {
        blogs: blogs[0].items,
      },
      revalidate: 60,
    };
  } catch (error) {
    console.error('Error fetching blog data:', error);
    return {
      props: {
        blogs: [],
      },
    };
  }
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, blogs }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Layout blogs={blogs}>
          {children}
        </Layout>
      </body>
    </html>
  );
}
